name = "SereneOrder"
author = "HIDDENSNOWER"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c4f84a8585f0fc9b70b99b04071ec4342ffa693fed6d286faa0cba905f011a7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
