name = "SereneOrder"
author = "HIDDENSNOWER"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d93e2535e43e020b79990f0d954d40383d904f3319895ec4b19a7602cdbd431"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
